---
coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 0%
        base: auto
        paths:
          - "src/cpps/"
    patch:
      default:
        target: 90%
        threshold: 0%
        base: auto
        paths:
          - "src/cpps/"
