---
name: Lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

  push:
    branches-ignore: [main]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Super Linter
        uses: github/super-linter/slim@v4.9.7
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CLANG_FORMAT: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
